// GENERATED by spec-generate — DO NOT EDIT (regenerate and commit; hand-edits fail `spec-generate check`)
// source: spec/models/MDL-order-lifecycle.statechart.json
// model-hash: sha256:3e87d6b65e1bc9535448009045b876d0faf12e611df75a90b5b42d60e4c37b1f
// undeclared_event_policy: error
//
// Diagram-as-oracle (RU spec §6.3): code stays hand-owned, this suite is
// generated. Every test is #[ignore]d until the application provides the
// StatechartSubject shim for this model — running with --ignored panics
// with the shim TODO rather than passing vacuously.
// Test bodies are #[rustfmt::skip]: identifier lengths come from the
// model, so rustfmt stability is declared, never chased per-name.

use spec_conformance_tests::statechart::{subject, Outcome};

const MODEL: &str = "order-lifecycle";

fn shim() -> Box<dyn spec_conformance_tests::statechart::StatechartSubject> {
    match subject(MODEL) {
        Some(s) => s,
        None => panic!("statechart shim for MDL-{MODEL} not implemented — application work"),
    }
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn transition_cancelling_on_refund_settled_to_cancelled() {
    let outcome = shim().apply("cancelling", "REFUND_SETTLED");
    assert_eq!(outcome, Outcome::Transition("cancelled".into()));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn transition_delivery_attempted_on_delivery_reported_to_delivered() {
    let outcome = shim().apply("delivery_attempted", "DELIVERY_REPORTED");
    assert_eq!(outcome, Outcome::Transition("delivered".into()));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn transition_delivery_attempted_on_retry_to_delivery_attempted() {
    let outcome = shim().apply("delivery_attempted", "RETRY");
    assert_eq!(outcome, Outcome::Transition("delivery_attempted".into()));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn transition_delivery_attempted_on_return_to_returned() {
    let outcome = shim().apply("delivery_attempted", "RETURN");
    assert_eq!(outcome, Outcome::Transition("returned".into()));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn transition_placed_on_cancel_to_cancelling() {
    let outcome = shim().apply("placed", "CANCEL");
    assert_eq!(outcome, Outcome::Transition("cancelling".into()));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn transition_placed_on_ship_to_shipped() {
    let outcome = shim().apply("placed", "SHIP");
    assert_eq!(outcome, Outcome::Transition("shipped".into()));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn transition_shipped_on_delivery_reported_to_delivered() {
    let outcome = shim().apply("shipped", "DELIVERY_REPORTED");
    assert_eq!(outcome, Outcome::Transition("delivered".into()));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn transition_shipped_on_retry_to_delivery_attempted() {
    let outcome = shim().apply("shipped", "RETRY");
    assert_eq!(outcome, Outcome::Transition("delivery_attempted".into()));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelled_on_cancel() {
    let outcome = shim().apply("cancelled", "CANCEL");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelled_on_delivery_reported() {
    let outcome = shim().apply("cancelled", "DELIVERY_REPORTED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelled_on_refund_settled() {
    let outcome = shim().apply("cancelled", "REFUND_SETTLED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelled_on_retry() {
    let outcome = shim().apply("cancelled", "RETRY");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelled_on_return() {
    let outcome = shim().apply("cancelled", "RETURN");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelled_on_ship() {
    let outcome = shim().apply("cancelled", "SHIP");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelling_on_cancel() {
    let outcome = shim().apply("cancelling", "CANCEL");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelling_on_delivery_reported() {
    let outcome = shim().apply("cancelling", "DELIVERY_REPORTED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelling_on_retry() {
    let outcome = shim().apply("cancelling", "RETRY");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelling_on_return() {
    let outcome = shim().apply("cancelling", "RETURN");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelling_on_ship() {
    let outcome = shim().apply("cancelling", "SHIP");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_delivered_on_cancel() {
    let outcome = shim().apply("delivered", "CANCEL");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_delivered_on_delivery_reported() {
    let outcome = shim().apply("delivered", "DELIVERY_REPORTED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_delivered_on_refund_settled() {
    let outcome = shim().apply("delivered", "REFUND_SETTLED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_delivered_on_retry() {
    let outcome = shim().apply("delivered", "RETRY");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_delivered_on_return() {
    let outcome = shim().apply("delivered", "RETURN");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_delivered_on_ship() {
    let outcome = shim().apply("delivered", "SHIP");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_delivery_attempted_on_cancel() {
    let outcome = shim().apply("delivery_attempted", "CANCEL");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_delivery_attempted_on_refund_settled() {
    let outcome = shim().apply("delivery_attempted", "REFUND_SETTLED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_delivery_attempted_on_ship() {
    let outcome = shim().apply("delivery_attempted", "SHIP");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_placed_on_delivery_reported() {
    let outcome = shim().apply("placed", "DELIVERY_REPORTED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_placed_on_refund_settled() {
    let outcome = shim().apply("placed", "REFUND_SETTLED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_placed_on_retry() {
    let outcome = shim().apply("placed", "RETRY");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_placed_on_return() {
    let outcome = shim().apply("placed", "RETURN");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_returned_on_cancel() {
    let outcome = shim().apply("returned", "CANCEL");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_returned_on_delivery_reported() {
    let outcome = shim().apply("returned", "DELIVERY_REPORTED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_returned_on_refund_settled() {
    let outcome = shim().apply("returned", "REFUND_SETTLED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_returned_on_retry() {
    let outcome = shim().apply("returned", "RETRY");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_returned_on_return() {
    let outcome = shim().apply("returned", "RETURN");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_returned_on_ship() {
    let outcome = shim().apply("returned", "SHIP");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_shipped_on_cancel() {
    let outcome = shim().apply("shipped", "CANCEL");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_shipped_on_refund_settled() {
    let outcome = shim().apply("shipped", "REFUND_SETTLED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_shipped_on_return() {
    let outcome = shim().apply("shipped", "RETURN");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_shipped_on_ship() {
    let outcome = shim().apply("shipped", "SHIP");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn invariant_no_new_picks_dispatched() {
    assert!(shim().invariant_holds("cancelling", "no_new_picks_dispatched"));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn invariant_proof_of_delivery_retained() {
    assert!(shim().invariant_holds("delivered", "proof_of_delivery_retained"));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn invariant_attempt_count_recorded() {
    assert!(shim().invariant_holds("delivery_attempted", "attempt_count_recorded"));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn invariant_total_is_server_derived() {
    assert!(shim().invariant_holds("placed", "total_is_server_derived"));
}
