// GENERATED by spec-generate — DO NOT EDIT (regenerate and commit; hand-edits fail `spec-generate check`)
// source: spec/models/MDL-order-lifecycle.statechart.json
// model-hash: sha256:8d9f1f8a86f4c04fae5fd8c9f07259005c247caf0fe19e2f119c56d6cb507d1b
// undeclared_event_policy: error
//
// Diagram-as-oracle (RU spec §6.3): code stays hand-owned, this suite is
// generated. Every test is #[ignore]d until the application provides the
// StatechartSubject shim for this model — running with --ignored panics
// with the shim TODO rather than passing vacuously.
// Test bodies are #[rustfmt::skip]: identifier lengths come from the
// model, so rustfmt stability is declared, never chased per-name.

use spec_conformance_tests::statechart::{subject, Outcome};

const MODEL: &str = "order-lifecycle";

fn shim() -> Box<dyn spec_conformance_tests::statechart::StatechartSubject> {
    match subject(MODEL) {
        Some(s) => s,
        None => panic!("statechart shim for MDL-{MODEL} not implemented — application work"),
    }
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn transition_cancelling_on_refund_settled_to_cancelled() {
    let outcome = shim().apply("cancelling", "REFUND_SETTLED");
    assert_eq!(outcome, Outcome::Transition("cancelled".into()));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn transition_placed_on_cancel_to_cancelling() {
    let outcome = shim().apply("placed", "CANCEL");
    assert_eq!(outcome, Outcome::Transition("cancelling".into()));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn transition_placed_on_ship_to_shipped() {
    let outcome = shim().apply("placed", "SHIP");
    assert_eq!(outcome, Outcome::Transition("shipped".into()));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelled_on_cancel() {
    let outcome = shim().apply("cancelled", "CANCEL");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelled_on_refund_settled() {
    let outcome = shim().apply("cancelled", "REFUND_SETTLED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelled_on_ship() {
    let outcome = shim().apply("cancelled", "SHIP");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelling_on_cancel() {
    let outcome = shim().apply("cancelling", "CANCEL");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelling_on_ship() {
    let outcome = shim().apply("cancelling", "SHIP");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_placed_on_refund_settled() {
    let outcome = shim().apply("placed", "REFUND_SETTLED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_shipped_on_cancel() {
    let outcome = shim().apply("shipped", "CANCEL");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_shipped_on_refund_settled() {
    let outcome = shim().apply("shipped", "REFUND_SETTLED");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_shipped_on_ship() {
    let outcome = shim().apply("shipped", "SHIP");
    assert_eq!(outcome, Outcome::Error);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn invariant_no_new_picks_dispatched() {
    assert!(shim().invariant_holds("cancelling", "no_new_picks_dispatched"));
}
