// GENERATED by spec-generate — DO NOT EDIT (regenerate and commit; hand-edits fail `spec-generate check`)
// source: spec/models/MDL-order-lifecycle.statechart.json
// model-hash: sha256:e3e73f60006278893ab0bb5a1225707014de51b5953855387b2dca04217a2a16
// undeclared_event_policy: ignore
//
// Diagram-as-oracle (RU spec §6.3): code stays hand-owned, this suite is
// generated. Every test is #[ignore]d until the application provides the
// StatechartSubject shim for this model — running with --ignored panics
// with the shim TODO rather than passing vacuously.
// Test bodies are #[rustfmt::skip]: identifier lengths come from the
// model, so rustfmt stability is declared, never chased per-name.

use spec_conformance_tests::statechart::{subject, Outcome};

const MODEL: &str = "order-lifecycle";

fn shim() -> Box<dyn spec_conformance_tests::statechart::StatechartSubject> {
    match subject(MODEL) {
        Some(s) => s,
        None => panic!("statechart shim for MDL-{MODEL} not implemented — application work"),
    }
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn transition_cancelling_on_cancel_complete_to_cancelled() {
    let outcome = shim().apply("cancelling", "CANCEL_COMPLETE");
    assert_eq!(outcome, Outcome::Transition("cancelled".into()));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn transition_pending_on_cancel_to_cancelling() {
    let outcome = shim().apply("pending", "CANCEL");
    assert_eq!(outcome, Outcome::Transition("cancelling".into()));
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelled_on_cancel() {
    let outcome = shim().apply("cancelled", "CANCEL");
    assert_eq!(outcome, Outcome::Ignored);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelled_on_cancel_complete() {
    let outcome = shim().apply("cancelled", "CANCEL_COMPLETE");
    assert_eq!(outcome, Outcome::Ignored);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_cancelling_on_cancel() {
    let outcome = shim().apply("cancelling", "CANCEL");
    assert_eq!(outcome, Outcome::Ignored);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn rejects_pending_on_cancel_complete() {
    let outcome = shim().apply("pending", "CANCEL_COMPLETE");
    assert_eq!(outcome, Outcome::Ignored);
}

#[test]
#[ignore = "statechart shim pending (application work) — see file header"]
#[rustfmt::skip]
fn invariant_no_new_shipments_dispatched() {
    assert!(shim().invariant_holds("cancelling", "no_new_shipments_dispatched"));
}
