"""Conformance generation (TASK-070…072, spec §5.6/§6.3). Everything emitted
here is deterministic (no timestamps — hash headers only), committed, and
guarded by `check`: committed output must byte-match regeneration, which is
both the staleness rule (stale = red) and the hand-edit ban."""

from __future__ import annotations

import json
import re
from pathlib import Path

from .store import Store

GENERATED_BANNER = "GENERATED by spec-generate — DO NOT EDIT (regenerate and commit; hand-edits fail `spec-generate check`)"


# ------------------------------------------------------------ constants (TASK-072)

def _const_name(dotted: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", dotted).upper()


def render_constants(store: Store, service: str) -> str:
    from .lints.base import manifest_value_leaves
    manifest = store.manifests()[service]
    leaves = manifest_value_leaves(manifest.raw.get("values") or {})
    lines = [
        f"// {GENERATED_BANNER}",
        f"// source: spec/manifests/{service}.manifest.yaml",
        f"// manifest-hash: {manifest.content_hash}",
        "//",
        "// Bound-source discipline (RU spec §5.3): application tests import these",
        "// instead of hardcoding numbers — a gated value change then fails loudly",
        "// instead of leaving a stale literal asserting the old bound.",
        "#![allow(dead_code)]",
        "",
    ]
    for dotted in sorted(leaves):
        value = leaves[dotted]
        name = _const_name(dotted)
        if isinstance(value, bool):
            lines.append(f"pub const {name}: bool = {str(value).lower()};")
        elif isinstance(value, int):
            lines.append(f"pub const {name}: u64 = {value};")
        elif isinstance(value, float):
            lines.append(f"pub const {name}: f64 = {value};")
        else:
            lines.append(f'pub const {name}: &str = "{value}";')
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------ statechart suite (TASK-070)

def _sanitize(token: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", token.lower()).strip("_")


def plan_model_suite(store: Store, model_id: str) -> dict:
    """Derive the neutral test plan for one model (contract:
    interfaces/test-plan.schema.json).

    THIS is where every decision about what must be checked lives — which
    transitions, which undeclared pairs get rejected, which invariants are
    probed, and in what order. A per-stack emitter turns the plan into
    idiomatic tests and decides nothing. That split is what lets a second
    language cost an emitter rather than a generator.
    """
    model = store.models()[model_id]
    raw = model.raw
    states = raw["states"]
    alphabet = sorted({re.sub(r"\(.*\)$", "", e)
                       for s in states.values() for e in (s.get("on") or {})})
    policy = raw["undeclared_event_policy"]

    checks: list[dict] = []
    for state in sorted(states):
        for event, target in sorted((states[state].get("on") or {}).items()):
            bare = re.sub(r"\(.*\)$", "", event)
            checks.append({
                "kind": "transition",
                "id": f"transition_{_sanitize(state)}_on_{_sanitize(bare)}_to_{_sanitize(target)}",
                "from": state, "event": bare, "to": target,
            })
    for state in sorted(states):
        declared = {re.sub(r"\(.*\)$", "", e) for e in (states[state].get("on") or {})}
        for event in alphabet:
            if event in declared:
                continue
            checks.append({
                "kind": "rejection",
                "id": f"rejects_{_sanitize(state)}_on_{_sanitize(event)}",
                "state": state, "event": event,
                "expect": "ignored" if policy == "ignore" else "error",
            })
    for state in sorted(states):
        invariant = states[state].get("invariant")
        if invariant:
            checks.append({
                "kind": "invariant",
                "id": f"invariant_{_sanitize(invariant)}",
                "state": state, "name": invariant,
            })

    return {
        "model": model_id,
        "model_hash": model.content_hash,
        "undeclared_event_policy": policy,
        "verified_by": sorted(
            ru.id for ru in store.rus() if ru.status == "active"
            and any(e.get("type") == "model" and e.get("ref") == f"MDL-{model_id}"
                    for e in ru.raw.get("verification") or [])),
        "checks": checks,
    }


def render_test_plan(store: Store) -> str:
    payload = {"contract_version": 1,
               "models": [plan_model_suite(store, m) for m in store.models()]}
    return json.dumps(payload, indent=2) + "\n"


def render_model_suite(store: Store, model_id: str) -> str:
    """Rust emitter — renders the neutral plan as an idiomatic cargo suite."""
    return emit_rust_suite(plan_model_suite(store, model_id))


def emit_rust_suite(plan: dict) -> str:
    model_id = plan["model"]
    policy = plan["undeclared_event_policy"]
    out = [
        f"// {GENERATED_BANNER}",
        f"// source: spec/models/MDL-{model_id}.statechart.json",
        f"// model-hash: {plan['model_hash']}",
        f"// undeclared_event_policy: {policy}",
        "//",
        "// Diagram-as-oracle (RU spec §6.3): code stays hand-owned, this suite is",
        "// generated. Every test is #[ignore]d until the application provides the",
        "// StatechartSubject shim for this model (plan D-P6.4) — running with",
        "// --ignored panics with the shim TODO rather than passing vacuously.",
        "// Test bodies are #[rustfmt::skip]: identifier lengths come from the",
        "// model, so rustfmt stability is declared, never chased per-name.",
        "",
        "use spec_conformance_tests::statechart::{subject, Outcome};",
        "",
        f'const MODEL: &str = "{model_id}";',
        "",
        "fn shim() -> Box<dyn spec_conformance_tests::statechart::StatechartSubject> {",
        "    match subject(MODEL) {",
        "        Some(s) => s,",
        '        None => panic!("statechart shim for MDL-{MODEL} not implemented — application work"),',
        "    }",
        "}",
        "",
    ]
    ignore = '#[ignore = "statechart shim pending (application work) — see file header"]'
    skip = "#[rustfmt::skip]"  # model-derived names can exceed any line width
    for check in plan["checks"]:
        if check["kind"] == "transition":
            body = [
                f'    let outcome = shim().apply("{check["from"]}", "{check["event"]}");',
                f'    assert_eq!(outcome, Outcome::Transition("{check["to"]}".into()));',
            ]
        elif check["kind"] == "rejection":
            outcome = "Outcome::Ignored" if check["expect"] == "ignored" else "Outcome::Error"
            body = [
                f'    let outcome = shim().apply("{check["state"]}", "{check["event"]}");',
                f"    assert_eq!(outcome, {outcome});",
            ]
        else:
            body = [f'    assert!(shim().invariant_holds("{check["state"]}", "{check["name"]}"));']
        out += ["#[test]", ignore, skip, f"fn {check['id']}() {{", *body, "}", ""]
    return "\n".join(out)


# ------------------------------------------------------------ targets & check

def targets(store: Store, root: Path) -> dict[Path, str]:
    """Every generated artifact and its current rendering. Where the
    conformance crate lives comes from rqunit.toml ([stacks.rust]
    conformance_crate); projection paths are store contract (§12.1), fixed."""
    from .config import load as load_config
    crate_rel = load_config(root).rust.conformance_crate
    out: dict[Path, str] = {}
    crate = root / crate_rel
    mods = []
    for service, manifest in store.manifests().items():
        if manifest.raw.get("values"):
            mod = f"values_{service.replace('-', '_')}"
            mods.append(mod)
            out[crate / "src" / "generated" / f"{mod}.rs"] = render_constants(store, service)
    mod_lines = [f"// {GENERATED_BANNER}", ""] + [f"pub mod {m};" for m in sorted(mods)]
    out[crate / "src" / "generated" / "mod.rs"] = "\n".join(mod_lines) + "\n"
    trace_map: dict[str, list[str]] = {}
    package = Path(crate_rel).name  # crate basename = package name (config contract)
    for model_id in store.models():
        plan = plan_model_suite(store, model_id)
        stem = f"generated_mdl_{model_id.replace('-', '_')}"
        out[crate / "tests" / f"{stem}.rs"] = emit_rust_suite(plan)
        # Generated suites carry no per-test annotations — their trace is
        # inherited from the model's RU links via this sidecar (formats §5).
        # Read from the PLAN, not from the emitted source: check identity is a
        # property of the plan, and every emitter must preserve it.
        for check in plan["checks"]:
            trace_map[f"{package}::{stem}::{check['id']}"] = plan["verified_by"]
    out[root / "spec" / "projections" / "trace-map.json"] = json.dumps(
        {"_": GENERATED_BANNER, "checks": dict(sorted(trace_map.items()))}, indent=2) + "\n"
    out[root / "spec" / "projections" / "test-plan.json"] = render_test_plan(store)
    out[root / "spec" / "projections" / "ru-index.json"] = render_ru_index(store)
    for service in store.manifests():
        out[root / "spec" / "projections" / "surface-sheets" / f"{service}.md"] = \
            render_sheet_file(store, service)
    return out


# ------------------------------------------------------------ index + sheets (TASK-090, §11)

def render_ru_index(store: Store) -> str:
    """formats §7, minus generated_at/store_commit (plan D-P8.1: determinism
    for a committed, check-guarded projection). Search hits this, never the
    directory."""
    from .assemble import _computed_label
    from .parser.tokens import extract
    rus = []
    for ru in store.rus():
        scope = ru.raw.get("scope") or {}
        tokens, _ = extract(ru.raw["statement"])
        rus.append({
            "id": ru.id,
            "status": ru.status,
            "tier": ru.tier,
            "computed": _computed_label(store, ru),
            "tags": ru.raw.get("tags") or [],
            "feature": ru.raw.get("feature"),
            "owns": scope.get("owns") or [],
            "must_not_touch": scope.get("must_not_touch") or [],
            "verification_types": sorted({e["type"] for e in ru.raw.get("verification") or []}),
            "manifest_refs": sorted({f"{t.kind}:{(t.qualifier + '/') if t.qualifier else ''}{t.key}"
                                     for t in tokens}),
        })
    return json.dumps({"_": GENERATED_BANNER, "rus": rus}, indent=2) + "\n"


def render_sheet_file(store: Store, service: str) -> str:
    from .assemble import render_surface_sheet
    lines = [f"# Surface sheet — {service}",
             f"<!-- {GENERATED_BANNER} -->", ""]
    lines += render_surface_sheet(store, service)
    return "\n".join(lines) + "\n"


def write_all(store: Store, root: Path) -> list[Path]:
    written = []
    for path, content in targets(store, root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text() != content:
            path.write_text(content)
            written.append(path)
    return written


def check_current(store: Store, root: Path) -> list[str]:
    """Stale or hand-edited generated files (§5.6: stale = red; hand-edit ban)."""
    problems = []
    for path, content in targets(store, root).items():
        if not path.exists():
            problems.append(f"missing generated file: {path}")
        elif path.read_text() != content:
            problems.append(f"stale or hand-edited generated file: {path}")
    return problems


# ------------------------------------------------------------ literal scan (advisory)

def scan_literals(store: Store, root: Path) -> list[str]:
    from .config import load as load_config
    from .lints.base import manifest_value_leaves
    findings = []
    values = {}
    for service, manifest in store.manifests().items():
        for dotted, value in manifest_value_leaves(manifest.raw.get("values") or {}).items():
            if isinstance(value, int) and not isinstance(value, bool) and abs(value) >= 10:
                values.setdefault(value, []).append(f"{service}:{dotted}")
    dirs = sorted({d for pattern in load_config(root).rust.literal_scan
                   for d in Path(root).glob(pattern) if d.is_dir()})
    for tests_dir in dirs:
        for rs in sorted(tests_dir.glob("*.rs")):
            text = rs.read_text()
            for value, keys in values.items():
                for m in re.finditer(rf"\b{value}\b", text):
                    line = text.count("\n", 0, m.start()) + 1
                    findings.append(
                        f"{rs.relative_to(root)}:{line}: literal {value} equals manifest "
                        f"value {', '.join(keys)} — import the generated constant instead")
                    break  # one advisory per (file, value)
    return findings
