"""Conformance generation (TASK-070…072, spec §5.6/§6.3). Everything emitted
here is deterministic (no timestamps — hash headers only), committed, and
guarded by `check`: committed output must byte-match regeneration, which is
both the staleness rule (stale = red) and the hand-edit ban."""

from __future__ import annotations

import json
import re
from pathlib import Path

from .store import Store

GENERATED_BANNER = "GENERATED by spec-generate — DO NOT EDIT (regenerate and commit; hand-edits fail `spec-generate check`)"


# ------------------------------------------------------------ statechart suite (TASK-070)

def _sanitize(token: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", token.lower()).strip("_")


def plan_model_suite(store: Store, model_id: str) -> dict:
    """Derive the neutral test plan for one model (contract:
    interfaces/test-plan.schema.json).

    THIS is where every decision about what must be checked lives — which
    transitions, which undeclared pairs get rejected, which invariants are
    probed, and in what order. A per-stack emitter turns the plan into
    idiomatic tests and decides nothing. That split is what lets a second
    language cost an emitter rather than a generator.
    """
    from .model_rules import require_sound
    require_sound(store, model_id)   # a model violating the dialect must not render
    model = store.models()[model_id]
    raw = model.raw
    states = raw["states"]
    alphabet = sorted({re.sub(r"\(.*\)$", "", e)
                       for s in states.values() for e in (s.get("on") or {})})
    policy = raw["undeclared_event_policy"]

    checks: list[dict] = []
    for state in sorted(states):
        for event, target in sorted((states[state].get("on") or {}).items()):
            bare = re.sub(r"\(.*\)$", "", event)
            checks.append({
                "kind": "transition",
                "id": f"transition_{_sanitize(state)}_on_{_sanitize(bare)}_to_{_sanitize(target)}",
                "from": state, "event": bare, "to": target,
            })
    for state in sorted(states):
        declared = {re.sub(r"\(.*\)$", "", e) for e in (states[state].get("on") or {})}
        for event in alphabet:
            if event in declared:
                continue
            checks.append({
                "kind": "rejection",
                "id": f"rejects_{_sanitize(state)}_on_{_sanitize(event)}",
                "state": state, "event": event,
                "expect": "ignored" if policy == "ignore" else "error",
            })
    for state in sorted(states):
        invariant = states[state].get("invariant")
        if invariant:
            checks.append({
                "kind": "invariant",
                "id": f"invariant_{_sanitize(invariant)}",
                "state": state, "name": invariant,
            })

    return {
        "model": model_id,
        "model_hash": model.content_hash,
        "undeclared_event_policy": policy,
        "verified_by": sorted(
            ru.id for ru in store.rus() if ru.status == "active"
            and any(e.get("type") == "model" and e.get("ref") == f"MDL-{model_id}"
                    for e in ru.raw.get("verification") or [])),
        "checks": checks,
    }


def render_test_plan(store: Store) -> str:
    payload = {"contract_version": 1,
               "models": [plan_model_suite(store, m) for m in store.models()]}
    return json.dumps(payload, indent=2) + "\n"


# ------------------------------------------------------------ targets & check

def emit_request(store: Store, stack) -> dict:
    """Everything an emitter may know (contract: emit-request.schema.json).
    The plan decides what must be checked; the constants carry each
    value-holding manifest's leaves and hash; `options` is the stack's own
    passthrough table, handed as data so emission stays a pure function of
    the request."""
    from .lints.base import manifest_value_leaves
    constants = {}
    for service, manifest in store.manifests().items():
        leaves = manifest_value_leaves(manifest.raw.get("values") or {})
        if leaves:
            constants[service] = {"manifest_hash": manifest.content_hash,
                                  "values": leaves}
    return {"contract_version": 1,
            "plan": json.loads(render_test_plan(store)),
            "constants": constants,
            "options": stack.options}


def _apply_response(root: Path, stack, plan: dict, response: dict,
                    out: dict, trace_map: dict) -> None:
    """Validate one emitter's answer and stage its files. Check identity
    comes from the plan: an unmapped plan check, an invented one, or a
    double-mapped one is a contract violation — this mapping is what the
    trace map inherits RU links through (formats §5)."""
    from .errors import BadConfig
    where = f"[stacks.{stack.name}.adapter] emitter"
    planned = {(m["model"], c["id"]): m["verified_by"]
               for m in plan["models"] for c in m["checks"]}
    seen = set()
    for entry in response["checks"]:
        key = (entry["model"], entry["plan_id"])
        if key not in planned:
            raise BadConfig(where, f"emitter mapped a check the plan does not contain "
                                   f"({key[0]}::{key[1]}) — check identity comes from "
                                   "the plan, never invented (§6.3)")
        if key in seen:
            raise BadConfig(where, f"emitter mapped {key[0]}::{key[1]} twice — every "
                                   "plan check renders as exactly one test (§6.3)")
        seen.add(key)
        trace_map[entry["id"]] = planned[key]
    missing = sorted(set(planned) - seen)
    if missing:
        shown = ", ".join(f"{m}::{c}" for m, c in missing[:5])
        raise BadConfig(where, f"emitter left {len(missing)} plan check(s) unmapped "
                               f"({shown}) — a rendered suite must carry the whole "
                               "plan (§6.3)")
    for entry in response["files"]:
        relative = entry["path"]
        parts = Path(relative).parts
        if Path(relative).is_absolute() or ".." in parts:
            raise BadConfig(where, f"emitted path '{relative}' escapes the consumer "
                                   "root — paths are root-relative and normalized")
        target = root / relative
        if target in out:
            raise BadConfig(where, f"two emitters produced '{relative}' — a generated "
                                   "file has exactly one producer")
        out[target] = entry["content"]


def missing_emitter(store: Store, root: Path) -> str | None:
    """The teaching message for a store whose models nothing can render.
    `rqunit generate` treats this as a tool error — generated suites silently
    not existing is the failure mode — while verbs that merely refresh
    projections (activation, scaffolding) regenerate what they can."""
    from .config import load as load_config
    if store.models() and not any(s.adapter.emitter is not None
                                  for s in load_config(root).stacks):
        return ("this store carries statechart models, but no declared stack has "
                "an emitter role — generated suites would silently not exist. "
                "Declare [stacks.<name>.adapter] emitter = { cmd = [...] } (build "
                "the adapter in its own toolchain) or { artifact = \"path\" } in "
                "rqunit.toml (§6.3)")
    return None


def targets(store: Store, root: Path) -> dict[Path, str]:
    """Every generated artifact and its current rendering. Suites and
    constants come from each declared stack's emitter role (files as data;
    CORE writes them); projection paths are store contract (§12.1), fixed."""
    from .config import load as load_config
    from .invoke import run_role
    config = load_config(root)
    emitting = [s for s in config.stacks if s.adapter.emitter is not None]
    out: dict[Path, str] = {}
    trace_map: dict[str, list[str]] = {}
    for stack in emitting:
        request = emit_request(store, stack)
        response = run_role(root, stack, "emitter", schema="emitted-files.schema.json",
                            stdin_payload=json.dumps(request))
        _apply_response(root, stack, request["plan"], response, out, trace_map)
    # When models exist but nothing emitted them, the trace map is omitted
    # rather than staged empty: a lenient projection refresh (activation,
    # scaffolding) must not silently clobber committed inherited traces —
    # `rqunit generate` reports the missing emitter as a tool error instead.
    if not (store.models() and not emitting):
        out[root / "spec" / "projections" / "trace-map.json"] = json.dumps(
            {"_": GENERATED_BANNER, "checks": dict(sorted(trace_map.items()))}, indent=2) + "\n"
    out[root / "spec" / "projections" / "test-plan.json"] = render_test_plan(store)
    out[root / "spec" / "projections" / "ru-index.json"] = render_ru_index(store)
    for service in store.manifests():
        out[root / "spec" / "projections" / "surface-sheets" / f"{service}.md"] = \
            render_sheet_file(store, service)
    return out


# ------------------------------------------------------------ index + sheets (TASK-090, §11)

def render_ru_index(store: Store) -> str:
    """formats §7, minus generated_at/store_commit (plan D-P8.1: determinism
    for a committed, check-guarded projection). Search hits this, never the
    directory."""
    from .assemble import _computed_label
    from .parser.tokens import extract
    rus = []
    for ru in store.rus():
        scope = ru.raw.get("scope") or {}
        tokens, _ = extract(ru.raw["statement"])
        rus.append({
            "id": ru.id,
            "status": ru.status,
            "tier": ru.tier,
            "computed": _computed_label(store, ru),
            "tags": ru.raw.get("tags") or [],
            "feature": ru.raw.get("feature"),
            "owns": scope.get("owns") or [],
            "must_not_touch": scope.get("must_not_touch") or [],
            "verification_types": sorted({e["type"] for e in ru.raw.get("verification") or []}),
            "manifest_refs": sorted({f"{t.kind}:{(t.qualifier + '/') if t.qualifier else ''}{t.key}"
                                     for t in tokens}),
        })
    return json.dumps({"_": GENERATED_BANNER, "rus": rus}, indent=2) + "\n"


def render_sheet_file(store: Store, service: str) -> str:
    from .assemble import render_surface_sheet
    lines = [f"# Surface sheet — {service}",
             f"<!-- {GENERATED_BANNER} -->", ""]
    lines += render_surface_sheet(store, service)
    return "\n".join(lines) + "\n"


def write_all(store: Store, root: Path) -> list[Path]:
    written = []
    for path, content in targets(store, root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text() != content:
            path.write_text(content)
            written.append(path)
    return written


def check_current(store: Store, root: Path) -> list[str]:
    """Stale or hand-edited generated files (§5.6: stale = red; hand-edit ban).

    Both messages carry their fix. `missing` is the state a store is in before
    it has ever generated, and a bare path with no verb sends the reader to the
    source to find out what produces it.
    """
    problems = []
    for path, content in targets(store, root).items():
        try:
            where = path.relative_to(root)
        except ValueError:
            where = path
        if not path.exists():
            problems.append(
                f"missing generated file: {where}\n"
                "    Run `rqunit generate all` and commit the result. Generated artifacts are "
                "committed and currency-checked, so a store that has never generated is "
                "reported as out of date rather than assumed empty (§5.6).")
        elif path.read_text() != content:
            problems.append(
                f"stale or hand-edited generated file: {where}\n"
                "    Run `rqunit generate all` and commit the result. If you edited this file "
                "by hand, the edit is lost by design — change what generates it (§5.6).")
    return problems


# ------------------------------------------------------------ literal scan (advisory)

def scan_literals(store: Store, root: Path) -> list[str]:
    from .config import load as load_config
    from .lints.base import manifest_value_leaves
    findings = []
    values = {}
    for service, manifest in store.manifests().items():
        for dotted, value in manifest_value_leaves(manifest.raw.get("values") or {}).items():
            if isinstance(value, int) and not isinstance(value, bool) and abs(value) >= 10:
                values.setdefault(value, []).append(f"{service}:{dotted}")
    # The sweep globs *.rs, so only the rust stack's literal_scan participates
    # until the advisory moves behind an adapter role — unioning every stack's
    # globs here would report clean for stacks the sweep never looked at.
    stack = load_config(root).stack("rust")
    dirs = sorted({d for pattern in (stack.literal_scan if stack else ())
                   for d in Path(root).glob(pattern) if d.is_dir()})
    for tests_dir in dirs:
        for rs in sorted(tests_dir.glob("*.rs")):
            text = rs.read_text()
            for value, keys in values.items():
                for m in re.finditer(rf"\b{value}\b", text):
                    line = text.count("\n", 0, m.start()) + 1
                    findings.append(
                        f"{rs.relative_to(root)}:{line}: literal {value} equals manifest "
                        f"value {', '.join(keys)} — import the generated constant instead")
                    break  # one advisory per (file, value)
    return findings
