//! Suite emission — the Rust adapter's emitter role (contracts: rqunit
//! `interfaces/emit-request.schema.json` in, `emitted-files.schema.json` out).
//!
//! RENDERING ONLY. The request's plan decided which checks exist, what each
//! asserts, and their identity and order; this module decides nothing but how
//! that reads in Rust. It is a pure function of the request — no store, no
//! filesystem walk — and core writes the files it returns, which is what
//! keeps the hand-edit ban and `generate check` idempotency in one place.

use std::path::Path;

use serde_json::{json, Map, Value};

use crate::Result;

const BANNER: &str = "GENERATED by spec-generate — DO NOT EDIT (regenerate and commit; hand-edits fail `spec-generate check`)";

pub fn respond(request_json: &str) -> Result<String> {
    let request: Value =
        serde_json::from_str(request_json).map_err(|e| format!("parse emit request: {e}"))?;
    // Absent means the conventional default; PRESENT and malformed is an
    // error — a typo silently bent into the default would emit a crate the
    // consumer never asked for, and the currency gate would bless it.
    let crate_rel = match &request["options"]["conformance_crate"] {
        Value::Null => "spec-conformance-tests".to_string(),
        Value::String(s) if !s.is_empty() => s.clone(),
        _ => return Err("conformance_crate must be a non-empty string path".into()),
    };
    let package = Path::new(&crate_rel)
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .ok_or("conformance_crate has no basename")?;

    let mut files: Vec<(String, String)> = Vec::new();
    let mut checks: Vec<Value> = Vec::new();

    // Constants: one module per value-carrying service, plus the mod root.
    let empty = Map::new();
    let constants = request["constants"].as_object().unwrap_or(&empty);
    let mut mods: Vec<String> = Vec::new();
    for (service, entry) in constants {
        let module = format!("values_{}", service.replace('-', "_"));
        files.push((
            format!("{crate_rel}/src/generated/{module}.rs"),
            render_constants(service, entry)?,
        ));
        mods.push(module);
    }
    mods.sort();
    let mod_lines: Vec<String> = std::iter::once(format!("// {BANNER}"))
        .chain(std::iter::once(String::new()))
        .chain(mods.iter().map(|m| format!("pub mod {m};")))
        .collect();
    files.push((
        format!("{crate_rel}/src/generated/mod.rs"),
        format!("{}\n", mod_lines.join("\n")),
    ));

    // Statechart suites: one cargo test file per model in the plan.
    for plan in request["plan"]["models"].as_array().into_iter().flatten() {
        let model = plan["model"].as_str().ok_or("plan entry without model")?;
        let stem = format!("generated_mdl_{}", model.replace('-', "_"));
        files.push((format!("{crate_rel}/tests/{stem}.rs"), render_suite(plan)?));
        for check in plan["checks"].as_array().into_iter().flatten() {
            let plan_id = check["id"].as_str().ok_or("plan check without id")?;
            checks.push(json!({
                "model": model,
                "plan_id": plan_id,
                "id": format!("{package}::{stem}::{plan_id}"),
            }));
        }
    }

    files.sort_by(|a, b| a.0.cmp(&b.0));
    let files: Vec<Value> = files
        .into_iter()
        .map(|(path, content)| json!({"path": path, "content": content}))
        .collect();
    let response = json!({
        "contract_version": 1,
        "generated_by": format!("rqunit-adapter-rust emit-suite {}", env!("CARGO_PKG_VERSION")),
        "files": files,
        "checks": checks,
    });
    serde_json::to_string_pretty(&response)
        .map(|s| s + "\n")
        .map_err(|e| format!("render emit response: {e}").into())
}

fn const_name(dotted: &str) -> String {
    dotted
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn render_constants(service: &str, entry: &Value) -> Result<String> {
    let hash = entry["manifest_hash"]
        .as_str()
        .ok_or("constants without manifest_hash")?;
    let mut lines = vec![
        format!("// {BANNER}"),
        format!("// source: spec/manifests/{service}.manifest.yaml"),
        format!("// manifest-hash: {hash}"),
        "//".to_string(),
        "// Bound-source discipline (RU spec §5.3): application tests import these".to_string(),
        "// instead of hardcoding numbers — a gated value change then fails loudly".to_string(),
        "// instead of leaving a stale literal asserting the old bound.".to_string(),
        "#![allow(dead_code)]".to_string(),
        String::new(),
    ];
    let empty = Map::new();
    let values = entry["values"].as_object().unwrap_or(&empty);
    let mut dotted: Vec<&String> = values.keys().collect();
    dotted.sort();
    for key in dotted {
        let name = const_name(key);
        let value = &values[key];
        let line = match value {
            Value::Bool(b) => format!("pub const {name}: bool = {b};"),
            Value::Number(n) if n.is_f64() => format!("pub const {name}: f64 = {n};"),
            Value::Number(n) => format!("pub const {name}: u64 = {n};"),
            Value::String(s) => format!("pub const {name}: &str = \"{s}\";"),
            other => return Err(format!("constant {key} has non-scalar value {other}").into()),
        };
        lines.push(line);
    }
    Ok(format!("{}\n", lines.join("\n")))
}

fn render_suite(plan: &Value) -> Result<String> {
    let model = plan["model"].as_str().ok_or("plan entry without model")?;
    let hash = plan["model_hash"]
        .as_str()
        .ok_or("plan entry without model_hash")?;
    let policy = plan["undeclared_event_policy"]
        .as_str()
        .ok_or("plan entry without undeclared_event_policy")?;
    let mut out = vec![
        format!("// {BANNER}"),
        format!("// source: spec/models/MDL-{model}.statechart.json"),
        format!("// model-hash: {hash}"),
        format!("// undeclared_event_policy: {policy}"),
        "//".to_string(),
        "// Diagram-as-oracle (RU spec §6.3): code stays hand-owned, this suite is".to_string(),
        "// generated. Every test is #[ignore]d until the application provides the".to_string(),
        "// StatechartSubject shim for this model (plan D-P6.4) — running with".to_string(),
        "// --ignored panics with the shim TODO rather than passing vacuously.".to_string(),
        "// Test bodies are #[rustfmt::skip]: identifier lengths come from the".to_string(),
        "// model, so rustfmt stability is declared, never chased per-name.".to_string(),
        String::new(),
        "use spec_conformance_tests::statechart::{subject, Outcome};".to_string(),
        String::new(),
        format!("const MODEL: &str = \"{model}\";"),
        String::new(),
        "fn shim() -> Box<dyn spec_conformance_tests::statechart::StatechartSubject> {".to_string(),
        "    match subject(MODEL) {".to_string(),
        "        Some(s) => s,".to_string(),
        "        None => panic!(\"statechart shim for MDL-{MODEL} not implemented — application work\"),".to_string(),
        "    }".to_string(),
        "}".to_string(),
        String::new(),
    ];
    let ignore = "#[ignore = \"statechart shim pending (application work) — see file header\"]";
    let skip = "#[rustfmt::skip]"; // model-derived names can exceed any line width
    for check in plan["checks"].as_array().into_iter().flatten() {
        let text = |key: &str| -> Result<&str> {
            check[key]
                .as_str()
                .ok_or_else(|| format!("plan check missing '{key}'").into())
        };
        let body = match text("kind")? {
            "transition" => vec![
                format!(
                    "    let outcome = shim().apply(\"{}\", \"{}\");",
                    text("from")?,
                    text("event")?
                ),
                format!(
                    "    assert_eq!(outcome, Outcome::Transition(\"{}\".into()));",
                    text("to")?
                ),
            ],
            "rejection" => {
                let outcome = if text("expect")? == "ignored" {
                    "Outcome::Ignored"
                } else {
                    "Outcome::Error"
                };
                vec![
                    format!(
                        "    let outcome = shim().apply(\"{}\", \"{}\");",
                        text("state")?,
                        text("event")?
                    ),
                    format!("    assert_eq!(outcome, {outcome});"),
                ]
            }
            _ => vec![format!(
                "    assert!(shim().invariant_holds(\"{}\", \"{}\"));",
                text("state")?,
                text("name")?
            )],
        };
        out.push("#[test]".to_string());
        out.push(ignore.to_string());
        out.push(skip.to_string());
        out.push(format!("fn {}() {{", text("id")?));
        out.extend(body);
        out.push("}".to_string());
        out.push(String::new());
    }
    Ok(out.join("\n"))
}
